SAMPLE_RATE = 24000
CONFIG_FILENAME = 'config.yml'
EPOCH_FILENAME = 'epochs_2nd_00020.pth'
MODEL_URL = 'https://drive.google.com/uc?id=1jK_VV3TnGM9dkrIMsdQ_upov8FrIymr7'
MODEL_PATH = 'Models/LibriTTS/'
NLTK_DATA_PATH = 'Data/nltk/'
TOKENIZERS_PATH = NLTK_DATA_PATH + 'tokenizers/'
PUNKT_PATH = TOKENIZERS_PATH + 'punkt/PY3/english.pickle'
PUNKT_URL = 'https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/tokenizers/punkt.zip'
REFERENCE_PATH = 'Data/reference_audio/'
OUTPUT_PATH = 'Output/'