CONFIG_FILENAME = 'config.yml'
MODEL_URL = 'https://drive.google.com/uc?id=1jK_VV3TnGM9dkrIMsdQ_upov8FrIymr7'
MODEL_PATH = 'Models/LibriTTS/'
PRETRAINED_MODEL_PATH = MODEL_PATH + 'epochs_2nd_00020.pth'
NLTK_DATA_PATH = 'Data/nltk/'
TOKENIZERS_PATH = NLTK_DATA_PATH + 'tokenizers/'
PUNKT_PATH = TOKENIZERS_PATH + 'punkt/PY3/english.pickle'
PUNKT_URL = 'https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/tokenizers/punkt.zip'
REFERENCE_PATH = 'Data/reference_audio/'
OUTPUT_PATH = '/Users/andrew/.bin/arena/src/assets/kotor/dialog/'
PROMPT_HISTORY_PATH = OUTPUT_PATH + 'prompt_history.csv'